
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: music_tracking
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: music_tracking_development

test:
  <<: *default
  database: music_tracking_test

production:
  <<: *default
  database: music_tracking_production
